#!/usr/bin/env node

/**
 * PERFORMANCE BUDGET ENFORCEMENT - HRthis System
 * ==============================================
 * 
 * This script checks if the built bundle meets our performance budgets.
 * It fails the build if budgets are exceeded.
 * 
 * Usage:
 *   node scripts/HRTHIS_performanceBudgetCheck.js
 * 
 * Requires:
 *   - npm run build (must be run first)
 *   - dist/stats.json (generated by vite-bundle-visualizer)
 * 
 * Exit codes:
 *   0 = All budgets met ✅
 *   1 = Budgets exceeded ❌
 * 
 * Part of Phase 5 - Priority 1 - Performance Budgets
 * 
 * @version 1.0.0
 * @since 2025-01-10
 */

const fs = require('fs');
const path = require('path');

// ============================================================================
// CONFIGURATION
// ============================================================================

const BUDGETS = {
  bundles: {
    main: {
      js: 512 * 1024,      // 512 KB
      css: 100 * 1024,     // 100 KB
    },
    vendor: {
      js: 300 * 1024,      // 300 KB
    },
    chunks: {
      perChunk: 200 * 1024, // 200 KB per chunk
    },
    initialLoad: {
      total: 512 * 1024,   // 512 KB total
    },
  },
};

// ============================================================================
// UTILITIES
// ============================================================================

const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
};

function colorize(text, color) {
  return `${colors[color]}${text}${colors.reset}`;
}

function formatBytes(bytes) {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${(bytes / Math.pow(k, i)).toFixed(2)} ${sizes[i]}`;
}

function formatPercent(value, total) {
  return `${((value / total) * 100).toFixed(1)}%`;
}

// ============================================================================
// BUNDLE ANALYSIS
// ============================================================================

function analyzeBuildDirectory() {
  const distPath = path.join(process.cwd(), 'dist');
  
  if (!fs.existsSync(distPath)) {
    console.error(colorize('\n❌ Error: dist/ directory not found', 'red'));
    console.error('   Please run "npm run build" first\n');
    process.exit(1);
  }
  
  const results = {
    mainJs: 0,
    mainCss: 0,
    vendorJs: 0,
    chunks: [],
    totalJs: 0,
    totalCss: 0,
    totalAssets: 0,
  };
  
  // Scan dist/assets/
  const assetsPath = path.join(distPath, 'assets');
  
  if (fs.existsSync(assetsPath)) {
    const files = fs.readdirSync(assetsPath);
    
    files.forEach(file => {
      const filePath = path.join(assetsPath, file);
      const stat = fs.statSync(filePath);
      const size = stat.size;
      
      // JavaScript files
      if (file.endsWith('.js')) {
        if (file.includes('vendor') || file.includes('react')) {
          results.vendorJs += size;
        } else if (file.includes('index') || file.includes('main')) {
          results.mainJs += size;
        } else {
          results.chunks.push({ name: file, size });
        }
        results.totalJs += size;
      }
      
      // CSS files
      if (file.endsWith('.css')) {
        if (file.includes('index') || file.includes('main')) {
          results.mainCss += size;
        }
        results.totalCss += size;
      }
      
      results.totalAssets += size;
    });
  }
  
  // Calculate initial load (main + vendor)
  results.initialLoad = results.mainJs + results.vendorJs + results.mainCss;
  
  return results;
}

// ============================================================================
// BUDGET CHECKING
// ============================================================================

function checkBudgets(results) {
  console.log('\n' + '='.repeat(80));
  console.log(colorize('  📊 PERFORMANCE BUDGET CHECK', 'bright'));
  console.log('='.repeat(80) + '\n');
  
  let failed = false;
  const warnings = [];
  
  // Check Main Bundle JS
  console.log(colorize('📦 Main Bundle (JavaScript):', 'cyan'));
  if (results.mainJs > BUDGETS.bundles.main.js) {
    console.log(colorize(`   ❌ FAIL: ${formatBytes(results.mainJs)} > ${formatBytes(BUDGETS.bundles.main.js)}`, 'red'));
    console.log(colorize(`      Over budget by ${formatBytes(results.mainJs - BUDGETS.bundles.main.js)}`, 'red'));
    failed = true;
  } else {
    const percentage = formatPercent(results.mainJs, BUDGETS.bundles.main.js);
    console.log(colorize(`   ✅ PASS: ${formatBytes(results.mainJs)} / ${formatBytes(BUDGETS.bundles.main.js)} (${percentage})`, 'green'));
  }
  
  // Check Main Bundle CSS
  console.log(colorize('\n🎨 Main Bundle (CSS):', 'cyan'));
  if (results.mainCss > BUDGETS.bundles.main.css) {
    console.log(colorize(`   ❌ FAIL: ${formatBytes(results.mainCss)} > ${formatBytes(BUDGETS.bundles.main.css)}`, 'red'));
    console.log(colorize(`      Over budget by ${formatBytes(results.mainCss - BUDGETS.bundles.main.css)}`, 'red'));
    failed = true;
  } else {
    const percentage = formatPercent(results.mainCss, BUDGETS.bundles.main.css);
    console.log(colorize(`   ✅ PASS: ${formatBytes(results.mainCss)} / ${formatBytes(BUDGETS.bundles.main.css)} (${percentage})`, 'green'));
  }
  
  // Check Vendor Bundle
  console.log(colorize('\n📚 Vendor Bundle (JavaScript):', 'cyan'));
  if (results.vendorJs > BUDGETS.bundles.vendor.js) {
    console.log(colorize(`   ❌ FAIL: ${formatBytes(results.vendorJs)} > ${formatBytes(BUDGETS.bundles.vendor.js)}`, 'red'));
    console.log(colorize(`      Over budget by ${formatBytes(results.vendorJs - BUDGETS.bundles.vendor.js)}`, 'red'));
    failed = true;
  } else {
    const percentage = formatPercent(results.vendorJs, BUDGETS.bundles.vendor.js);
    console.log(colorize(`   ✅ PASS: ${formatBytes(results.vendorJs)} / ${formatBytes(BUDGETS.bundles.vendor.js)} (${percentage})`, 'green'));
  }
  
  // Check Chunks
  console.log(colorize('\n📄 Lazy-Loaded Chunks:', 'cyan'));
  let chunksOk = true;
  
  if (results.chunks.length === 0) {
    console.log(colorize('   ℹ️  No lazy-loaded chunks found', 'yellow'));
  } else {
    results.chunks.forEach(chunk => {
      if (chunk.size > BUDGETS.bundles.chunks.perChunk) {
        console.log(colorize(`   ❌ ${chunk.name}: ${formatBytes(chunk.size)} > ${formatBytes(BUDGETS.bundles.chunks.perChunk)}`, 'red'));
        chunksOk = false;
        failed = true;
      } else {
        console.log(colorize(`   ✅ ${chunk.name}: ${formatBytes(chunk.size)}`, 'green'));
      }
    });
    
    if (chunksOk) {
      console.log(colorize(`   ✅ All ${results.chunks.length} chunks within budget`, 'green'));
    }
  }
  
  // Check Initial Load
  console.log(colorize('\n🚀 Initial Load (Critical Path):', 'cyan'));
  if (results.initialLoad > BUDGETS.bundles.initialLoad.total) {
    console.log(colorize(`   ❌ FAIL: ${formatBytes(results.initialLoad)} > ${formatBytes(BUDGETS.bundles.initialLoad.total)}`, 'red'));
    console.log(colorize(`      Over budget by ${formatBytes(results.initialLoad - BUDGETS.bundles.initialLoad.total)}`, 'red'));
    failed = true;
  } else {
    const percentage = formatPercent(results.initialLoad, BUDGETS.bundles.initialLoad.total);
    console.log(colorize(`   ✅ PASS: ${formatBytes(results.initialLoad)} / ${formatBytes(BUDGETS.bundles.initialLoad.total)} (${percentage})`, 'green'));
  }
  
  // Summary
  console.log('\n' + '='.repeat(80));
  console.log(colorize('  📈 SUMMARY', 'bright'));
  console.log('='.repeat(80) + '\n');
  
  console.log(`Total JavaScript:  ${formatBytes(results.totalJs)}`);
  console.log(`Total CSS:         ${formatBytes(results.totalCss)}`);
  console.log(`Total Assets:      ${formatBytes(results.totalAssets)}`);
  console.log(`Lazy Chunks:       ${results.chunks.length} chunks`);
  console.log(`Initial Load:      ${formatBytes(results.initialLoad)}`);
  
  console.log('\n' + '='.repeat(80));
  
  if (failed) {
    console.log(colorize('\n❌ PERFORMANCE BUDGETS EXCEEDED', 'red'));
    console.log(colorize('   Build failed due to budget violations\n', 'red'));
    
    console.log(colorize('💡 Suggestions to reduce bundle size:', 'yellow'));
    console.log('   1. Enable code splitting for large dependencies');
    console.log('   2. Lazy load heavy components (Charts, Canvas, etc.)');
    console.log('   3. Tree-shake unused code (especially icons)');
    console.log('   4. Use dynamic imports for large libraries');
    console.log('   5. Check for duplicate dependencies');
    console.log('   6. Minify and compress assets\n');
    
    return false;
  } else {
    console.log(colorize('\n✅ ALL PERFORMANCE BUDGETS MET', 'green'));
    console.log(colorize('   Build passed all budget checks\n', 'green'));
    return true;
  }
}

// ============================================================================
// DETAILED ANALYSIS
// ============================================================================

function printDetailedAnalysis(results) {
  console.log('\n' + '='.repeat(80));
  console.log(colorize('  📊 DETAILED ANALYSIS', 'bright'));
  console.log('='.repeat(80) + '\n');
  
  // Bundle breakdown
  console.log(colorize('Bundle Breakdown:', 'cyan'));
  console.log(`  Main JS:       ${formatBytes(results.mainJs)}`);
  console.log(`  Vendor JS:     ${formatBytes(results.vendorJs)}`);
  console.log(`  Main CSS:      ${formatBytes(results.mainCss)}`);
  console.log(`  Lazy Chunks:   ${formatBytes(results.chunks.reduce((sum, c) => sum + c.size, 0))}`);
  
  // Percentage breakdown
  const total = results.totalAssets;
  console.log(colorize('\nPercentage Breakdown:', 'cyan'));
  console.log(`  JavaScript:    ${formatPercent(results.totalJs, total)}`);
  console.log(`  CSS:           ${formatPercent(results.totalCss, total)}`);
  console.log(`  Other Assets:  ${formatPercent(total - results.totalJs - results.totalCss, total)}`);
  
  // Initial load breakdown
  console.log(colorize('\nInitial Load Breakdown:', 'cyan'));
  console.log(`  Main JS:       ${formatBytes(results.mainJs)} (${formatPercent(results.mainJs, results.initialLoad)})`);
  console.log(`  Vendor JS:     ${formatBytes(results.vendorJs)} (${formatPercent(results.vendorJs, results.initialLoad)})`);
  console.log(`  Main CSS:      ${formatBytes(results.mainCss)} (${formatPercent(results.mainCss, results.initialLoad)})`);
  
  // Top 5 largest chunks
  if (results.chunks.length > 0) {
    console.log(colorize('\nTop 5 Largest Chunks:', 'cyan'));
    const sortedChunks = [...results.chunks].sort((a, b) => b.size - a.size).slice(0, 5);
    sortedChunks.forEach((chunk, i) => {
      console.log(`  ${i + 1}. ${chunk.name}: ${formatBytes(chunk.size)}`);
    });
  }
  
  console.log('\n');
}

// ============================================================================
// MAIN
// ============================================================================

async function main() {
  console.log(colorize('\n🚀 Starting Performance Budget Check...', 'bright'));
  console.log(colorize('   HRthis System - Phase 5 Priority 1\n', 'cyan'));
  
  const startTime = Date.now();
  
  try {
    // Analyze build directory
    console.log('📁 Analyzing build directory...');
    const results = analyzeBuildDirectory();
    
    // Print detailed analysis
    printDetailedAnalysis(results);
    
    // Check budgets
    const passed = checkBudgets(results);
    
    // Time taken
    const duration = ((Date.now() - startTime) / 1000).toFixed(2);
    console.log(colorize(`⏱️  Budget check completed in ${duration}s\n`, 'cyan'));
    
    // Exit with appropriate code
    process.exit(passed ? 0 : 1);
    
  } catch (error) {
    console.error(colorize('\n❌ Budget check failed:', 'red'), error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

// Run
main();
